FROM public.ecr.aws/lambda/go:1.2021.04.09.16

RUN yum install -y golang
RUN go env -w GOPROXY=direct
ADD go.mod go.sum ./
RUN go mod download
# build
ADD ./main.go .
RUN go build -o ${LAMBDA_TASK_ROOT}/main

CMD [ "main" ]